### ISSUE TITLE
Testing with own ONNX model: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:image_tensor:0

### ISSUE THREAD

**Issue by ROBYER1** [asiryan/ssd_mobile_net_v1_csharp#1]
This looked like a very easy and nice way to test a onnx file quickly, however I get this error when testing out 
`object_detection_image_onnx.py`. I made sure to update the params for my own model!

```
Traceback (most recent call last):
  File "object_detection_image_onnx.py", line 22, in <module>
    result = sess.run(outputs, {"image_tensor:0": img_data})
  File "/home/robyer1/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 124, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:image_tensor:0
```

**Comment by asiryan** [comment]
Thank you for your issue! I fixed the repo, check this out.

**Comment by ROBYER1** [comment]
> Thank you for your issue! I fixed the repo, check this out.

Works now, thankyou! So easy to use too, I would suggest you change line 51 of object_detection_image_onnx.py to:

`font = ImageFont.truetype("arial.ttf", 22)`

and place the arial.ttf font in the same folder as the script, otherwise when running on Linux it errors out looking in C: drive for  a font (no C: drive on Linux)

**Comment by ROBYER1** [comment]
Actually, it only seems to work with the example and not any other onnx file despite me changing the parts of the python script, I get the same error for:

line 124, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:image_tensor:0

You can access my test onnx here: https://drive.google.com/file/d/1uY81Gh2Edh63R7G_6i5KI_oVLdMCuiem/view?usp=sharing

**Comment by ROBYER1** [comment]
I changed the input and output names to match, now I get a common ONNX error:

> [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (N11onnxruntime17PrimitiveDataTypeIhEE) , expected: (N11onnxruntime17PrimitiveDataTypeIfEE)

**Comment by asiryan** [comment]
> Actually, it only seems to work with the example and not any other onnx file despite me changing the parts of the python script, I get the same error for:
> 
> line 124, in run
> return self._sess.run(output_names, input_feed, run_options)
> onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:image_tensor:0
> 
> You can access my test onnx here: https://drive.google.com/file/d/1uY81Gh2Edh63R7G_6i5KI_oVLdMCuiem/view?usp=sharing

I looked at your archive, you are trying to run a completely different model - Yolo_v3. The thing is, my repository targets primarily on [TensorFlow Detection API](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md), **not Darknet/Yolo**. I can only recommend you look at the [TensorRT documentation](https://github.com/jkjung-avt/tensorrt_demos) or [FAQ](https://jkjung-avt.github.io/trt-yolov3-custom/) to understand how to run your own model.

**Comment by asiryan** [comment]
> > Thank you for your issue! I fixed the repo, check this out.
> 
> Works now, thankyou! So easy to use too, I would suggest you change line 51 of object_detection_image_onnx.py to:
> 
> `font = ImageFont.truetype("arial.ttf", 22)`
> 
> and place the arial.ttf font in the same folder as the script, otherwise when running on Linux it errors out looking in C: drive for a font (no C: drive on Linux)

Thank you, I'll replace it with the default python font :)

**Comment by ROBYER1** [comment]
> > Actually, it only seems to work with the example and not any other onnx file despite me changing the parts of the python script, I get the same error for:
> > line 124, in run
> > return self._sess.run(output_names, input_feed, run_options)
> > onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:image_tensor:0
> > You can access my test onnx here: https://drive.google.com/file/d/1uY81Gh2Edh63R7G_6i5KI_oVLdMCuiem/view?usp=sharing
> 
> I looked at your archive, you are trying to run a completely different model - Yolo_v3. The thing is, my repository targets primarily on [TensorFlow Detection API](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md), **not Darknet/Yolo**. I can only recommend you look at the [TensorRT documentation](https://github.com/jkjung-avt/tensorrt_demos) or [FAQ](https://jkjung-avt.github.io/trt-yolov3-custom/) to understand how to run your own model.

My apologies, I was thinking that .onnx files were meant to prevent such incompatibility by producing a standardised model for running these models, I am obviously wrong! Apologies for the hassle and I hope the font fix suggestion is helpful!

**Comment by asiryan** [comment]
> My apologies, I was thinking that .onnx files were meant to prevent such incompatibility by producing a standardised model for running these models, I am obviously wrong! Apologies for the hassle and I hope the font fix suggestion is helpful!

It would be great if it were so :)
It's okay, take a look at the Git repositories, I'm sure you will find what you are looking for, because yolo is very popular object detection model.
